name: Cypress Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (UI + API) on headless Chrome
        run: |
          npx cypress run --browser chrome --headless --reporter mochawesome \
            --reporter-options "reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true"

      - name: Generate HTML report
        run: |
          if [ -f cypress/reports/mochawesome/mochawesome.json ]; then
            npx marge cypress/reports/mochawesome/mochawesome.json \
              --reportDir cypress/reports/mochawesome --inline
          else
            echo "No JSON report found, skipping HTML generation"
          fi

      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/mochawesome
