name: Cypress Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run UI Tests
      run: npm run cypress:run:ui
    - name: Run API Tests
      run: npm run cypress:run:api
    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: cypress-reports
        path: cypress/reports/
