name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Roda todos os testes UI + API em modo headless no Chrome e gera Mochawesome
      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,json=true,html=true,overwrite=true

      # 5️⃣ Upload do relatório Mochawesome
      - name: Upload Cypress report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/mochawesome

      # 6️⃣ Upload de screenshots (caso existam)
      - name: Upload Cypress screenshots
        if: always() && hashFiles('cypress/screenshots/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 7️⃣ Upload de vídeos (caso existam)
      - name: Upload Cypress videos
        if: always() && hashFiles('cypress/videos/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
